tablite/core.py, tablite/version.py
Added the ability to hijack the progress tracking with tqdm patching
Removed throttling left by debugging
=> + support for text_encoder tqdm hijacking

tablite/core.py, tablite/version.py
Fix the exception thrown by an empty slice
=> Fix the exception thrown by an empty slice

tablite/core.py
=> * imputation tqdm

requirements.txt, tablite/utils.py, tablite/version.py, tests/test_api_basics.py
+ special slicing case with col[-1] becoming col[slice(-1, 0, 1)] which is wrong
=> Fix special case with -1 slicing

tablite/datatypes.py, tablite/version.py, tests/test_datatype.py
Added support for `datetime` <-> `date` for `DateType.infer` method.
=> datetime and date conversion support

changelog.md, tablite/core.py, tablite/version.py
`text_reader` tqdm tracks the entire process now. <br> `text_reader` properly respects free memory in *nix based systems. <br> `text_reader` no longer discriminates against hyperthreaded cores.
=> * changes to text_reader

tablite/core.py, tests/test_os.py
Should help with codeconv because methods didn't change and should be covered by existing tests the but coverage fell.
=> + tests for multi core

changelog.md, tablite/config.py, tablite/version.py
create temporary dir if missing
=> * create temporary dir if missing

changelog.md, tablite/core.py, tablite/h5py.py, tablite/memory_manager.py, tablite/version.py, tests/test_os.py, tests/test_slice_rules.py
Improve locking mechanism to allow retries when opening file as the previous solution could cause deadlocks when running multiple threads.
=> Improve locking mechanism

tablite/joins.py
=> * fix mp joins tqdm

tablite/base.py, tablite/sort_utils.py
=> + Table.load now has tqdm pbar

tablite/core.py, tablite/sortation.py, tablite/version.py
fix sortation tqdm not being passed
=> * fix sortation tqdm not being passed

tablite/base.py, tablite/datatypes.py, tablite/version.py, tests/test_api_basics.py
dtypes shouldnt crash on empty columns
=> *  dtypes shouldnt crash on empty columns

tablite/base.py, tablite/version.py
* repaginate will no longer trigger data type change on non-primitive
=> repagination datatype fix

tablite/file_reader_utils.py, tablite/version.py
get_headers now has text_qualifier
=> * get_headers now has text_qualifier

tablite/base.py, tablite/version.py
for the moment change the behaviour as described by #77  we can revert it because this is pre-release version and ducktype it for our own purposes instead
=> change slice behaviour as described by #77

tablite/redux.py, tablite/version.py
Added ability to do typesafe filter due to complaints that you cannot do filter on mixed type columns.
=> Filter is now typesafe

.github/workflows/publish.yml
A small fix in the publish script, republishing not necessary but nice to have in the future if windows build is fixed.
=> Small fix in the publish script

tablite/_nimlite/nimlite.nim, tablite/file_reader_utils.py, tablite/import_utils.py, tablite/utils.py, tablite/version.py
* fix xlsx headers
- remove tablite import echo
=> * fix headers

.gitignore, tablite/core.py, tablite/joins.py, tablite/merge.py, tests/test_api_basics.py, tests/test_join.py
Adding features:
All joins accept keyword "merge_keys"
Adding Table.merge which merges columns given a criteria.
=> Join w merge

changelog.md, requirements.txt, tablite/_nimlite/nimlite.nim, tablite/base.py, tablite/config.py, tablite/import_utils.py, tablite/mp_utils.py, tablite/nimlite.py, tablite/sortation.py, tablite/utils.py, tablite/version.py
Accessing page now updates it's timestamp
Page functionality has been split into `Page` and `SimplePage`.
It is now possible to disable cleanup mechanism.
Graduated to full release.
=> Accessing page updates timestamp

tablite/_nimlite/infertypes.nim, tablite/core.py, tablite/version.py, tests/data/booleans.csv, tests/test_filereader_formats.py
=> Boolean infer more flexible

.github/workflows/python-test.yml, tablite/_nimlite/pylayer.nim, tablite/config.py, tablite/version.py
=> Fix nim on windows!

tablite/_nimlite/funcs/column_selector.nim, tablite/_nimlite/funcs/column_selector/collectinfo.nim, tablite/_nimlite/nimlite.nim, tablite/nimlite.py, tablite/version.py
Fix issue with fail table column order and more granular tqdm
=> Fix issue with fail table column order and more granular tqdm

tablite/_nimlite/dateutils.nim, tablite/_nimlite/unpickling.nim, tablite/_nimlite/utils.nim, tablite/core.py
=> Added column selector docstrings

tablite/_nimlite/funcs/column_selector/sliceconv.nim, tablite/nimlite.py, tablite/version.py
Fix an issue with fully cast pages that get partially invalidated by other columns in the row.
=> Fix an issue with page that is already cast pages

tablite/_nimlite/funcs/column_selector/sliceconv.nim, tablite/version.py
last commit misplaced files by not placing them under /processing anymore, not really a bug but this is nicer
=> fix minor issue

tablite/_nimlite/nimlite.nim, tablite/_nimlite/nimlite.pyi, tablite/_nimlite/numpy.nim, tablite/_nimlite/unpickling.nim, tablite/base.py, tablite/core.py, tablite/diff.py, tablite/export_utils.py, tablite/groupbys.py, tablite/import_utils.py, tablite/imputation.py, tablite/joins.py, tablite/lookup.py, tablite/match.py, tablite/merge.py, tablite/nimlite.py, tablite/pivots.py, tablite/redux.py, tablite/reindex.py, tablite/sortation.py, tablite/version.py, tests/test_base.py
Fix an issue where join with merge keys produces an error
Fix an issue with nim unpickler and 16bit ints, pickle format always declares them as uint16
Added missing progressbar for filter
Reimplemented repagination in nim
=> Some bugfixes

tablite/_nimlite/funcs/text_reader/pylayer.nim, tablite/_nimlite/funcs/text_reader/table.nim, tablite/_nimlite/funcs/text_reader/taskargs.nim, tablite/_nimlite/funcs/text_reader/text_reader.nim, tablite/joins.py, tablite/nimlite.py, tablite/version.py, tests/test_join.py
=> Fix join issue

build_nim.sh, tablite/pivots.py, tablite/utils.py, tablite/version.py, tests/test_transpose.py
Fixed an issue with pivot transpose plus some minor utilities for table type determination.
=> Fix an issue with pivot_transpose + utils

nimlite/funcs/text_reader/csvparse.nim, nimlite/funcs/text_reader/pylayer.nim, nimlite/funcs/text_reader/text_reader.nim, nimlite/libnimlite.nim, nimlite/libnimlite.pyi, tablite/import_utils.py, tablite/nimlite.py, tablite/utils.py, tablite/version.py, tests/test_filereader_formats.py
Headers will not be part of skip_empty mechanism.
=> do not skip headers

tablite/import_utils.py, tablite/version.py, tests/test_filereader_formats.py
=> When sheet is not specified, assume first

tablite/imputation.py, tablite/version.py
Fix issue with imputation pbar
Fix issue with imputation statistics when table is predominantly the value you're trying to replace
=> Fix imputations

tablite/base.py, tablite/version.py, tests/test_imputation.py
=> fix an issue where imputation does not update page dtypes

nimlite.nimble, nimlite/funcs/filter.nim, nimlite/numpy.nim, tablite/redux.py, tablite/version.py
add back pythonic filter because we made assertions that noone uses non-primitive types and adding generic type support for non-primitive types non-trivial
=> fix timedeltas and non-primitive filter

tablite/redux.py, tablite/version.py
=> export some apis

tablite/export_utils.py, tablite/file_reader_utils.py, tablite/import_utils.py, tablite/utils.py, tablite/version.py
unify excel and text importer char stripping
=> fix text exporter

nimlite/funcs/filter.nim, nimlite/funcs/groupby.nim, nimlite/funcs/imputation.nim, nimlite/libnimlite.nim, nimlite/libnimlite.pyi, tablite/core.py, tablite/nimlite.py, tablite/sortation.py, tablite/version.py
Nim functions did not respect the passed pbars.
=> Respect passed pbars
