root-11/tablite

table/__init__.py, tests/filereader_tests.py
By setting `has_headers` to False, the first line in the file becomes the first row and each column gets its name based on its relative position.
=> Add has_headers parameter to text, excel, ods and log readers

tablite/core.py, tablite/version.py
Fixed a bug where the generic  `table.join(...)` would always throw because it already used object methods bound to `self`, causing the call to 
`f(**self**, other,left_keys,right_keys,left_columns,right_columns)` actually become a
`f(**self, self**, other,left_keys,right_keys,left_columns,right_columns)` call.
=> Fixed a bug related to join

tablite/core.py, tablite/version.py
Without unpacking `self.histogram()`, `column.statistics(self.histogram())` breaks with `TypeError: summary_statistics() missing 1 required positional argument: 'counts'`.
Added unpack symbol to fix this.
=> Column statistics fix

tablite/memory_manager.py, tablite/utils.py, tablite/version.py
Fixed some problems, where empty tables that have columns would throw an exception when `.statistics()` or `.show()` is called.
`.statistics()` now returns an empty dictionary (although maybe `None` is more appropriate?) as per discussion previously. 
`.show()` doesn't print `Empty table` as it would print with column-less empty table, but instead prints headers of the table with zero rows.
=> fix .statistics() and .show() exceptions on empty tables with columns

requirements.txt, tablite/core.py, tablite/version.py
Previous tqdm shunt did not shunt all of the tqdm instances, this replaces all tqdm instances with shunted ones and also adds tqdm progress tracking to some other places. Additionally, in some cases for example groupby and sort, pivot that depends on groupby can now share a progress bar instead of creating a new progress bar for each of the actions.
=> More shunts for tqdm/pbar

tablite/core.py, tablite/utils.py, tablite/version.py, tests/test_transpose.py, tests/test_utils.py
Renames `transpose()` to `pivot_transpose()` implements, `transpose()` and `T` for table transposition.
Fixes mode value calculation in string types.
Couldn't get the datetime test to work even in the original commits, suspect it has something to do with locales.
=> Pivot transpose and mode changes

changelog.md, tablite/core.py, tablite/version.py, tests/test_os.py
There was an arithmetic error that would trigger only on single core machines where the file would split up in too many tasks (1 task per 1 line if file fits fully in memory) causing the file reader to not only slow down significantly but also create way too many pages bloating the disk database.
=> * fix a nasty bug on single core systems

changelog.md, tablite/file_reader_utils.py, tablite/version.py
Some character encodings are just not feasible to distinguish without entire file analysis, allow safe failing and skip those characters.
=> Allow safe failing on invalid characters when reading header

changelog.md, tablite/file_reader_utils.py, tablite/version.py
`get_headers` now uses plain `openpyxl` instead of `pyexcel` wrapper to speed up fetch times ~10x on certain files.
=> * improve get_headers speeds on excel some files

changelog.md, requirements.txt, tablite/core.py, tablite/memory_manager.py, tablite/version.py, tests/test_memory_manager.py
`join` operation in both single and multiple process modes outputs now have parity.
`join` in multiple process modes no longer throws an exception when no matches are found.
`join` now creates tasks per 1M rows per column to reduce memory overhead. Further memory management could be added to avoid fetching the entire column for the sortation index.
Updated test suite to perform both single and multi-process test cases, not just single process.
=> Join changes

changelog.md, tablite/base.py, tablite/version.py, tests/test_base.py
Updated the way reference counting works. Tablite now tracks references to used pages and cleans them up based on number of references to those pages in the current process. This change allows to handle deep table clones when sending tables via processes (pickling/unpickling), whereas previous implementation would corrupt all tables using same pages due to reference counting asserting that all tables are shallow copies to the same object.
=> Fix refcount for deep table copies

changelog.md, tablite/file_reader_utils.py, tablite/version.py
Fix a logic bug in `get_headers` that caused one extra line to be returned than requested.
=> Fix get_headers linecount issue

changelog.md, tablite/file_reader_utils.py, tablite/version.py
Fix issues with `get_headers` falling back to text reading when reading 0 lines of excel, fix issue where reading excel file would ignore file count, excel file reader now has parity for linecount selection.
=> Fix xls get_headers

tablite/import_utils.py, tablite/version.py
Reasoning:
All modern processors have more than one thread per core intel has hyper-threading, amd has SMT. We don't want to gimp *nix because windows is incapable of doing something.
=> * enable logical cores on non windows machines

tablite/base.py, tablite/datatypes.py, tablite/file_reader_utils.py, tablite/import_utils.py, tablite/version.py, tests/test_filereader_formats.py
=> Performance improvements for text reader

tablite/datatypes.py, tablite/version.py
Inferring a string type as string should not become a none.
=> * fix none-ness for string inference

.gitignore, tablite/config.py, tablite/nimlite.py, tablite/version.py
Removed requirement to have `nim/nimble` installed for consuming the library, only needed for development now.
=> Removed the nim runtime requirement

tablite/_nimlite/paging.nim, tablite/import_utils.py, tablite/version.py
`np.take` produces a `<U1` from `<U0` array which causes internal np.array misalignment. Clamp the minimum string length to 1 so that unicode pages are always at least the size of `<U1` .
=> * resolve an issue with `np.take` and `<U0` dtype

tablite/_nimlite/csvparse.nim, tablite/_nimlite/encfile.nim, tablite/_nimlite/nimlite.nim, tablite/_nimlite/textreader.nim, tablite/config.py, tablite/import_utils.py, tablite/version.py, tests/data/split_lines.csv, tests/test_filereader_formats.py
Fixes the issue where some csvs had newline characters inbetween qualified (quoted) strings causing segfault when trying to load in numpy because the pages got mis-alligned.
Cannot be resolved in pythonic implementation (windows) because using `csv.parser` module locks python out from the file handler to know where the file reader head is.
=> Fix nimporter to support newlines in qualified strings

tablite/version.py
The dev version generated proper pyd's in the wheel.
=> Bump tablite version to 2023.8.7

nimlite.nimble, tablite/imputation.py, tablite/version.py
Fix inconsistencies with imputation three methods being in-place, meanwhile NN was copy. Most of the tablite functions are copy, so it makes more sense to change the other imputation methods to be copy too instead of changing the NN method to be inplace.
=> fix imputation inconsistency

nimlite.nimble, nimlite/funcs/column_selector/makepage.nim, nimlite/numpy.nim, nimlite/pymodules.nim, tablite/version.py
Fix an issue where layouts could potential get mismatched, never happened in column selector itself but managed to trigger it in functionality that uses `makePage` template directly.
Removed that unnecessary print statement.
=> Fix potential layout mismatch

tablite/imputation.py, tablite/sort_utils.py, tablite/version.py, tests/test_sort.py
`unix_sort` in sort utils does not work at the moment, because dictionary of unique values is returned. In cases, where integers 1, 0 are used with bools, Python will convert 1 or 0 to bool (bool is essentially an integer in Python) and incorrect dictionary will be returned.
=> fix unix_sort

nimlite/funcs/text_reader/csvparse.nim, nimlite/funcs/text_reader/file_tracker.nim, nimlite/funcs/text_reader/paging.nim, nimlite/funcs/text_reader/text_reader.nim, tablite/version.py
There was a bug that prevented opening more than `1024` columns because it was growing the wrong buffer. However, we could still running into OS limitation where there are too many columns in file to open all file handles, in that case it will fall back to deferred file tracking which will open columns on demand. This significantly degrades performance because files need to be opened, flushed and opened again for each column that wasn't yet open. This will do for now because the user is likely insane to have such large tables but there is still a faster solution where we further divide the horizontal slice dump task into vertical slice sub-tasks. But that solution is non-trivial, requires additional information about each vertical partition of each row to always be present in memory and …
=> add support for opening for any number of columns
